### ISSUE TITLE
Remove submodules from submodules to avoid recursive submodules

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel#10]
IF AND ONLY IF the other issues are solved so this META repository is working and will be sufficient to develop Qabel.

**Comment by thechauffeur** [comment]
CAUTION: You better wait until we discussed how we want to use Travis etc. because there are more things to update until this setup will work.

**Comment by thechauffeur** [comment]
To solve this issue the following issues must be solved beforehand.
* [ ] qabel-core (see Qabel/qabel-core#341)
* [ ] qabel-desktop (see Qabel/qabel-desktop#9)
* [ ] qabel-helloworld-module (see Qabel/qabel-helloworld-module#9)

**Comment by thechauffeur** [comment]
When the referenced PRs are merged this issue is solved.

**Comment by thechauffeur** [comment]
All submodules from submodules have been removed.
